config/routes.rb
Rails.application.routes.draw do

  resources :users, except: :index do
    #NOTE: this should represent CRUDing attendances
    resources :events
  end

  #NOTE: I would have another set of routes just `resources :events` (not nested) to allow the user to CRUD their own events.

  get "/events/:id", to: "events#show"

  get "/sign_in", to: "sessions#new"
  get "/sign_out", to: "sessions#destroy", as: 'sign_out'

  root 'welcome#index'
  post "/sessions", to: "sessions#create"
  #FIXME: the below route is not restful. you may want `post /users/:user_id/events` instead. Also it looks like it's already defined above for you with `resources`.
  post "/users/:user_id/events/:event_id", to: "attendances#joinEvent"
  get "/users/:user_id/events", to: "attendances#index", as: "user_events_test"


end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
	belongs_to :event
	belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :attendances
	has_many :users, through: :attendances
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_one :event
	has_many :attendances
	has_many :events, through: :attendances

	#OPTIMIZE: add some validations to your user


	def self.confirm(params)
    	@user = User.find_by({email: params[:email]})
    	@user.try(:authenticate, params[:password])
 	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
	def index
    	@user = User.find(params[:user_id])
   		@events = @user.events

  		render :index
  	end

	#FIXME: this should be `create`
	def joinEvent
			#TODO: nice job authorizing the user can only create an event for themselves
  		@user = current_user
  		@event = Event.find(params[:event_id])
  		@user.events.push(@event)
  		redirect_to  "/events/:event_id"

	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # before_action :swap_address_to_lat_long, only: :create

	def index
    	@user = User.find(params[:user_id])
    	@events = @user.events
	end

	def new
    	@event = Event.new
    	render :new
    end

  def create
      event_params = params.require(:event).permit(:game, :number_places, :user_id)
     #  lat_long = address_to_lat_long(event_params[:address])
      @event = Event.new(event_params)
     #  @event.lat = lat_long["lat"]
     #  @event.long = lat_long["long"]
     @event.user_id = current_user.id
        if @event.save
        redirect_to current_user # <-- go to show_user
      else
        #handle error
        render :new
      end

end
  
  def show
    @event = Event.find(params[:id])
    @allUsers = @event.users
    
  end
 
	

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	  def new
    @user = User.new
    render :new
    end

    def create
    user_params = params.require(:user).permit(:email, :password)
    @user = User.confirm(user_params)
    if @user
      login(@user)
      redirect_to "/users/#{@user.id}"
    else
      redirect_to "/sign_in"
    end
    end

  def destroy
    logout
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
    @users = User.all
		render :index
	end
	def new
    # we need to make
    # a new user
    # to pass to the
    # form later
    @user = User.new
    render :new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :address, :city, :email, :password, :true_or_false, :lat, :lng)
    @user = User.create(user_params)
    userAddressFull = @user.address+" , "+@user.city
    @coords = address_to_lat_long(userAddressFull)
    @user.update(:lat => @coords["lat"], :lng => @coords["lng"])
    login(@user) # <-- login the user
    redirect_to "/users/#{@user.id}" # <-- go to show
  end

  def show
    @user = User.find(params[:id])


    # @adress= User.find(params[:id]).address

    # grab all the hosts
    # @hosts = User.where(true_or_false: true)
    @events = Event.where.not(user_id: nil)

    @lats = user_lats
    @lngs = user_lngs
		#FIXME: I'd write more comments explaining this. I'm not sure what it's doing.
    @lats.count.times do |count|
      if @lats[count] == nil
        @lats[count] = @user.lat
      end
    end
    @lngs.count.times do |count|
      if @lngs[count] == nil
        @lngs[count] = @user.lng
      end
    end


    # hosts = User.where(true_or_false: true)
    # @host_addresses = hosts.map do |host|
    #   address_to_lat_long(host.address)
    # end

    # @events=Event.all
    render :show
  end

  private

  def user_lats
    lats = @events.map do |e|
      e.user.lat
    end
  end

  def user_lngs
    lngs = @events.map do |e|
      e.user.lng
    end
  end

  def address_to_lat_long(address)
      # @event.lat = lat_long["lat"]
      # @event.long = lat_long["long"]
      res = HTTParty.get("https://maps.googleapis.com/maps/api/geocode/json?address=" + address, verify: false).parsed_response
      res["results"][0]["geometry"]["location"]
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    if current_user == nil
      redirect_to "/sign_in"
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end

  def new
    @user = User.new
    render :new
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/index.html.erb
<div id ="joining">
	<h1>People who are joining</h1>
	<h3></h3>
	
</div>

<!-- comand z -->

app/views/events/new.html.erb
<div></div>

<%= form_for @event, url: user_events_path(current_user), method: "post" do |f| %>
  <div class="login">
    <%= f.text_field :game, placeholder: "game", class:'form' %>
     <br />

    <%= f.text_field :number_places, placeholder: "Places", class:'form' %>
    <br />
    <%= f.submit "Create", class:'button' %>
  </div>
  
<% end %> 

<!-- comand z -->

app/views/events/show.html.erb
<div class="list">
<h1><%= @event.game %></h1>

<h2>You are joing the game!</h2>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project2</title>
  
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag params[:controller], media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header id="header">
    
        <% if current_user %>
          <%= link_to "Logout", sign_out_path %>
          <% if current_user.true_or_false == true %>

          <%= link_to "Create", new_user_event_path(current_user) %>
          <% end %>
          <%=  link_to current_user.first_name, current_user %> 
          
          
        <% else %>
          <%= link_to "Login", sign_in_path %>
          <%= link_to "Home", root_path %>
          
        <% end %>
       
      
        
    
  </header>


<%= yield %>
<footer>
    <p>Developed by Luca Spezzano</p>
  
</footer>

</body>
</html>

app/views/users/index.html.erb
<div>
There are currently <%= @users.length %> signed_up
</div>

app/views/users/new.html.erb
Sign Up

<%= form_for @user do |f| %>
  <div class="signup">
    <%= f.text_field :first_name, placeholder: "First Name", class:'form' %>
  
    <%= f.text_field :last_name, placeholder: "Last Name", class:'form' %>
  
    <%= f.password_field :password, placeholder: "Password", class:'form' %>

    <%= f.text_field :address, placeholder: "Address", class:'form' %>

    <%= f.text_field :city, placeholder: "City", class:'form' %>
 
    <%= f.email_field :email, placeholder: "Email", class:'form' %>
  <br />
   
    <%= f.select(:true_or_false, options_for_select([['Host', true], ['Guest', false]])) %>
 
    
    <br />
     <%= f.submit "Sign Up", class:'button' %>
  </div>
 
<% end %> 

app/views/users/show.html.erb
<div class="user">
<div class="overlay" onClick="style.pointerEvents='none'"></div>

 </div>
  </div>
<%= javascript_tag do %>
  window.hosts = JSON.parse('<%= raw @hosts.to_json %>');
<% end %>

<!-- <div id="pop_event">
  <h2><%= @user.first_name + " " + @user.last_name %></h2>
   <h2> </h2>
    <button class="restart2">
      <h3>Join</h3>
    </button>
  


</div>
 -->
 
<!-- refactor script tags later -->
<script src="https://maps.googleapis.com/maps/api/js?callback=initMap" async></script>

<!-- script tags -->

<!-- if a host -->
<% if current_user.true_or_false %>
<div id="map"></div>
 
<script>

function renderMarks(options) {
  var lat = options.lat;
  var lng = options.lng;
  var game = options.game;
  var places = options.places;
  var user = options.id;
  var eventID = options.eventID;
  var marker = new google.maps.Marker({
    position: {lat: lat, lng: lng},
    map: map,
    title: 'Your map'
  });

var contentString = '<h2>' + game + "<br />" + " Places: " + places + "<br />" + "<a class='button1' href='/users/"+ user +"/events/"+eventID+"'>" + "Join" + '</a>' + '</h2>';

  var infowindow = new google.maps.InfoWindow({
    content: contentString
  });

  marker.addListener('click', function() {
    infowindow.open(map, marker);
  });        
 
}

var mapDiv = document.getElementById('map');
var map, infowindow;

function initMap(){
    
  map = new google.maps.Map(mapDiv, {
    center: {lat: <%=@user["lat"]%>,  lng: <%=@user["lng"]%>},
    zoom: 13
  });
  
  var userMarker = new google.maps.Marker({
      position: {lat:<%=@user["lat"]%>, lng:<%=@user["lng"]%>},
      map: map,
      title: 'Your map'
    });

  var contentString = '<h2>' + 'No event' + '</h2>';
  var infowindow = new google.maps.InfoWindow({
    content: contentString
  });

  userMarker.addListener('click', function() {
    infowindow.open(map, userMarker);
  });

  <% @events.each_with_index do |event, count| %>
    var eventOptions = {
      lat: <%= @lats[count] %>,
      lng: <%= @lngs[count] %>,
      game: <%= raw event.game.to_json %>,
      places: <%= raw event.number_places.to_json %>,
      id: <%= @user.id %>,
      eventID: <%= event.id %>
    }
    renderMarks(eventOptions);

    
  <% end %>
}  
      
</script>




<!-- if a guest -->




  <% else %>
    
    <div id="map"></div>
 
<script>

function renderMarks(options) {
  var lat = options.lat;
  var lng = options.lng;
  var game = options.game;
  var places = options.places;
  var user = options.id;
  var eventID = options.eventID;
  var marker = new google.maps.Marker({
    position: {lat: lat, lng: lng},
    map: map,
    title: 'Your map'
  });

  var contentString = '<h2>' + game + "<br />" + " Places: " + places + "<br />" + "<a class='button1' href='/users/"+ user +"/events/"+eventID+"'>" + "Join" + '</a>' + '</h2>';
  var infowindow = new google.maps.InfoWindow({
    content: contentString
  });

  marker.addListener('click', function() {
    infowindow.open(map, marker);
  });        
 
}

var mapDiv = document.getElementById('map');
var map, infowindow;

function initMap(){
    
  map = new google.maps.Map(mapDiv, {
    center: {lat: <%=@user["lat"]%>,  lng: <%=@user["lng"]%>},
    zoom: 13
  });
  
  

  <% @events.each_with_index do |event, count| %>
    var eventOptions = {
      lat: <%= @lats[count] %>,
      lng: <%= @lngs[count] %>,
      game: <%= raw event.game.to_json %>,
      places: <%= raw event.number_places.to_json %>,
      id: <%= @user.id %>,
      eventID: <%= event.id %>
    }
    renderMarks(eventOptions);
  <% end %>
}  
      
</script>

<% end %>

<div id="find_some_one">
  <h3>Find your neighbor !</h3>
  <p>Look who is around you and join the game of your team!</p>
</div>

app/views/welcome/index.html.erb
<head>
<link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
</head>
<script type="text/javasript">
	(function () {
		var documentEl = $(document),
		parralexBg = $('div.parallex');

		documentEl.on('scroll', function() {
			var currScrollPos = documentEl.scollTop();
			parallaxBg.css('background-position', '0' + -currScrollPos/4 + 'px');
		});
	})();
  
</script>
<div class="main">
     <div class="parallex">
		<hr width="60%">
		<h1>Together is better !</h1>
		<hr width="60%">
		<br />
       <%= link_to "Sign Up", new_user_path, class:'button' %>
	 </div>
   
</div>

<div id="how_it_works">

<h2>How it works</h2>
<p>HOST</p>
<p>The adress will appear on the map and you are able to create an event that the guests are able to join. </p>
<p>When you have created the event you have only wait that some guest will join you.</p>
<p>GUEST</p>
<p>The adress will not appear on the map and you are able to join the event created from the hosts. </p>
<p>You can find the host most near to you and join the event clicking on the marker of the map</p>
       
   
</div>

<div id="television">

<h2>Benefits</h2>
<h3>Host</h3>
<p>Make new friends.</p>
<p>Enjoy the game of your favourite team with someone else.</p>
<p>Have fun</p>
<p>Not anymore alone</p>
<h3>Guest</h3>
<p>Make new friends.</p>
<p>Watch the game of your team for free.</p>
<p>Have fun.</p>


       
   
</div>